# Generated by Django 5.1.6 on 2025-02-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('degree', models.CharField(max_length=200)),
                ('specialist', models.CharField(blank=True, max_length=200, null=True)),
                ('aadhar', models.CharField(max_length=20, unique=True)),
                ('certificate', models.FileField(upload_to='doctor_certificates/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('clinic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('clinic_address', models.TextField(blank=True, null=True)),
                ('clinic_number', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_suggestion', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('contact_through_app', models.BooleanField(default=False)),
            ],
        ),
    ]
