# Generated by Django 5.1.6 on 2025-02-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('contact_number', models.CharField(max_length=20)),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('family_history', models.TextField(blank=True, null=True)),
                ('diet', models.CharField(choices=[('Balanced', 'Balanced diet'), ('Junk', 'Mostly junk'), ('Balanced but occasional junk', 'Balanced but occasionally junk')], max_length=50)),
                ('exercise_per_week', models.PositiveIntegerField(default=0)),
                ('smoke', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Sometimes', 'Sometimes')], max_length=20)),
                ('smoke_frequency', models.PositiveIntegerField(blank=True, null=True)),
                ('drink', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Sometimes', 'Sometimes')], max_length=20)),
                ('drink_frequency', models.PositiveIntegerField(blank=True, null=True)),
                ('medical_doc_type', models.CharField(blank=True, choices=[('CT Scan', 'CT Scan'), ('X-ray', 'X-ray'), ('Blood Test', 'Blood Test'), ('MRI', 'MRI'), ('Ultrasound', 'Ultrasound'), ('ECG', 'ECG'), ('Others', 'Others')], max_length=50, null=True)),
                ('medical_doc', models.FileField(blank=True, null=True, upload_to='medical_reports/')),
            ],
        ),
    ]
