# Generated by Django 5.1.6 on 2025-02-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
