# Generated by Django 5.1.6 on 2025-03-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_rename_clinic_contact_number_doctor_clinic_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clinic_city',
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_City',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
