# Generated by Django 5.1.6 on 2025-03-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_remove_doctor_clinic_city_doctor_clinic_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='clinic_City',
            new_name='Clinic_City',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='clinic_Contact_Number',
            new_name='Clinic_Contact_Number',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='clinic_address',
            new_name='Clinic_address',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='clinic_name',
            new_name='Clinic_name',
        ),
    ]
