# Generated by Django 5.1.6 on 2025-03-05 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_rename_clinic_city_doctor_clinic_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Clinic_name',
            new_name='Clinic_Name',
        ),
    ]
